### PR TITLE
ZipFileExtensions

### PR DESCRIPTION
**Pull request by alexleen**
[ZipFileExtensions](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfileextensions?view=netframework-4.7.2)

Allows for use of ZipFileExtensions without accessing the Instance property.

### CODE REVIEW

**Comment by alexleen** [comment]
@jozefizso please review and merge at your earliest convenience.

**Comment by jozefizso** [comment]
It looks good. I'm just curious why are both .csproj files completly changed? It's whitespace changes or something like that?

**Comment by jozefizso** [comment]
When I download the patch file, the `.csproj` files contain `CRLF` line endings. They should have `LF` in the diff.

**Comment by alexleen** [comment]
Oh, good catch. Fixed.

**Comment by alexleen** [comment]
Ready to merge, @jozefizso?

**Pull request merged**
